name: deploy-to-fedora-s-1vcpu-1gb-sgp1-01
on: [workflow_dispatch]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pulling latest code
        working-directory: /opt/crypto-robo
        run: |
          echo "GIT RESET & PULL"
          git reset --hard HEAD && git pull origin main
      - name: Build image
        working-directory: /opt/crypto-robo
        run: |
          echo "REBUILD IMAGE"
          BUILD_TIME=$(date +%s)
          podman build -t weirdprogram-crypto-robo:latest -t weirdprogram-crypto-robo:${BUILD_TIME} .
      - name: Restart weirdprogram-crypto-robo-3000
        working-directory: /opt/crypto-robo
        run: |
          echo "RESTART weirdprogram-crypto-robo-3000"
          podman stop weirdprogram-crypto-robo-3000
          podman run --rm -it \
          -w /usr/src/crypto-robo/app \
          -p 3000:3000 \
          --name weirdprogram-crypto-robo-3000 \
           weirdprogram-crypto-robo:latest npm run dev