name: learn-github-actions
on: [workflow_dispatch]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Pulling latest code
        working-directory: /opt/crypto-robo
        run: |
          echo "GIT RESET & PULL"
          sudo git reset --hard HEAD && sudo git pull origin main
      - name: Build image
        working-directory: /opt/crypto-robo
        run: |
          echo "REBUILD IMAGE"
          BUILD_TIME=$(date +%s)
          podman build -t weirdprogram-crypto-robo:${BUILD_TIME}
