name: learn-github-actions
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: My first step
        working-directory: /opt/crypto-robo
        run: |
          echo "HELLO GITHUB ACTIONS"
          touch /opt/actions-runner/weirdprogram_crypto-robo.txt
      - name: My second step
        working-directory: /opt/crypto-robo
        run: |
          echo "GIT PULL"
          sudo git reset --hard HEAD && git pull origin main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

