name: learn-github-actions
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: My first step
        shell: bash
        run: |
          echo "HELLO GITHUB ACTIONS"
          touch /opt/actions-runner/weirdprogram_crypto-robo.txt
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
